### PR TITLE
Dmrpp gen

### PR DESCRIPTION
**Pull request by jgallagher59701**
This branch introduces the build_dmrpp.py command that can build a DMR++ document using the DMR++ Builder as a Service and then upload the DMR++ document to an S3 bucket.

### CODE REVIEW

**Review by sawer297 — APPROVED** [review]
looks good, i vote to merge

**Review by kneumiller — CHANGES_REQUESTED** [review]
I like the changes with the build_dmrpp.py command. However, it appears several tests are failing.

**Comment by jgallagher59701** [comment]
> I like the changes with the build_dmrpp.py command. However, it appears several tests are failing.

Yeah, I have no idea why, either. They work on my local machine. We'll have to sort this out.

**Comment by Mikejmnez** [comment]
Looks like the failing tests are not associated with this PR, but rather the previous PR #24 that never got resolved before merging onto `main`. The current [commit](https://github.com/OPENDAP/pydmr/commit/9f0ff9bdd6c389d3768e0dd94807e671dfe38dd0) on `main` also shows the same failures.

**Review by kneumiller — APPROVED** [review]
Looks good to me!

**Pull request merged**
